### ISSUE TITLE
Importing snippet should include all state information

### ISSUE THREAD

**Issue by thebho** [maryvilledev/codesplainUI#79] opened 2017-03-02 14:58 UTC
Currently missing:
- [x] Lock state
- [x] Token Highlights Checked
- [ ] Previously Annotated lines

**Comment by solkaz** [comment] 2017-03-02 15:04
If a snippet has been saved, then we can assume that it is locked, no?

**Comment by thebho** [comment] 2017-03-02 15:06
Interesting question.  Probably, yes.  This is more about pulling up a saved snippet and having to re lock/highlight/etc...

**Comment by dane-johnson** [comment] 2017-03-02 15:14
Presently this distinction is not made.

**Comment by dane-johnson** [comment] 2017-03-02 15:33
Duplicate of #77

**Comment by thebho** [comment] 2017-03-02 15:33
Added another feature that was missing from the Redis imports.

**Comment by dane-johnson** [comment] 2017-03-02 15:34
Duplicate of #86

**Comment by thebho** [comment] 2017-03-02 15:36
Fair enough, closing this

**Closed** 2017-03-02 15:36 UTC
Labels: bug, ready, Redis Saving
