### ISSUE TITLE
Fix CSS errors in console

### ISSUE THREAD

**Issue by thebho** [maryvilledev/codesplainUI#99] opened 2017-03-02 17:19 UTC
![pasted image at 2017_03_02 11_14 am](https://cloud.githubusercontent.com/assets/12362348/23518740/16dcf414-ff3a-11e6-9397-74477f97086a.png)

**Comment by solkaz** [comment] 2017-03-29 14:57
Are these still occurring? I have not seen them anywhere.

**Comment by dane-johnson** [comment] 2017-03-29 19:23
Seems like dead issue to me.

**Comment by dane-johnson** [comment] 2017-03-30 20:08
Closing as Could Not Reproduce.

**Closed by dane-johnson** 2017-03-30 20:08 UTC
Labels: bug, Optimization, ready
