### ISSUE TITLE
Highlighting is not updating when saving over a snippet

### ISSUE THREAD

**Issue by thebho** [maryvilledev/codesplainUI#370] opened 2017-04-07 21:12 UTC
## Expected Behavior
When I save a snippet that was already saved, the current highlight state should be updated in S3

## Current Behavior
Highlighting is persisting from the original save

## Steps to Reproduce (for bugs)
1. Save a snippet
2. Change the highlighting and save (PUT) the snippet
3. Reload the page

**Comment by thebho** [comment] 2017-04-07 21:14
And now the behavior is WAI.  So this is inconsistently not working

**Comment by Hopding** [comment] 2017-04-10 22:21
I tested this in dev, and am not able to reproduce the behavior. Have you encountered the problem since posting this issue?

**Comment by thebho** [comment] 2017-04-11 13:58
It's still working as intended in Dev

**Comment by Hopding** [comment] 2017-04-11 21:47
Closing because cannot reproduce.

**Comment by thebho** [comment] 2017-04-11 22:32
Not working in Dev again

**Closed** 2017-04-12 20:40 UTC
Labels: bug, ready, Snippet Saving
